### ISSUE TITLE
Could not find gem 

### ISSUE THREAD

**Issue by techinpark** [grab/cocoapods-binary-cache#12]
# What is Problem ? :mag:
- I added one line in my `Gemfile` 
```ruby
gem 'coccoapods-binary-cache', :git => 'https://github.com/grab/cocoapods-binary-cache.git', :tag => '0.0.3'
```
- try command `bundle install` 

- Result 
```sh
Fetching https://github.com/grab/cocoapods-binary-cache.git
Fetching gem metadata from https://rubygems.org/........
Could not find gem 'coccoapods-binary-cache' in https://github.com/grab/cocoapods-binary-cache.git (at 0.0.3@e0782bc).
The source does not contain any versions of 'coccoapods-binary-cache'
```

# My Environment 💻 
- version: ruby (2.6.4) 
- version: cocoapods (1.8.4) 
- version : python (3.7.7)

**Comment by trinhngocthuyen** [comment]
Hi @techinpark there was a typo `coccoapods-binary-cache`, which I believe is the cause of this issue.

I have revised the README. it looks like the typo was in that file. I'll update it.
Regards

**Comment by techinpark** [comment]
@trinhngocthuyen Thanks for comment. Installation is done. but have other issue. 
When I tried binary-cache command just show up cocoapods help. 
can you help me? 
```sh 
$ pod binary-cache --cmd=prebuild

[!] Unknown command: `binary-cache`
Did you mean: cache?
```

**Comment by techinpark** [comment]
I solved it myself.


```
$ bundle exec pod binary-cache --cmd=prebuild
```

When tried this command It works,
but found a new **error.** 

```sh 
ModuleNotFoundError: No module named 'colorlog'
```

- Solution 
```sh
$ pip3 install colorlog
```

Now it works. :smile:

**Comment by dcristolovean** [comment]
Still doesn't work for me.
1) it wasn't the typo, I had the gem correctly set up.
2) pod binary-cache --cmd=prebuild
[!] Unknown command: `binary-cache`

3) using bundle exec pod binary-cache --cmd=prebuild
Indeed, I also had to install colorlog, but after that, I'm getting other errors:

bundle exec pod binary-cache --cmd=prebuild
BinaryCache run: prebuild
Traceback (most recent call last):
  File "/Users/danielcristolovean/.bundle/ruby/2.6.0/cocoapods-binary-cache-e0782bcb5e85/lib/command/PythonScripts/prebuild_lib_cli.py", line 34, in <module>
    main()
  File "/Users/danielcristolovean/.bundle/ruby/2.6.0/cocoapods-binary-cache-e0782bcb5e85/lib/command/PythonScripts/prebuild_lib_cli.py", line 31, in main
    raise e
  File "/Users/danielcristolovean/.bundle/ruby/2.6.0/cocoapods-binary-cache-e0782bcb5e85/lib/command/PythonScripts/prebuild_lib_cli.py", line 18, in main
    config = PrebuildConfig(args.config_path)
  File "/Users/danielcristolovean/.bundle/ruby/2.6.0/cocoapods-binary-cache-e0782bcb5e85/lib/command/PythonScripts/prebuild_config.py", line 28, in __init__
    raise e
  File "/Users/danielcristolovean/.bundle/ruby/2.6.0/cocoapods-binary-cache-e0782bcb5e85/lib/command/PythonScripts/prebuild_config.py", line 12, in __init__
    config = json.load(f)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 86 (char 87)

**Comment by bigbangvn** [comment]
Hi @dcristolovean Looks like you haven't created `PodBinaryCacheConfig.json` (mentioned the README file)

**Comment by dcristolovean** [comment]
I surely did, but there might've been some errors into it. I didn't have time to check it in the last days, but Monday I'm back on this and if it still doesn't work, I'll ask here about.
Thanks for the responses so far.

**Comment by bigbangvn** [comment]
@dcristolovean looks like you're using quite old version. Please try 0.1.2

Gemfile:

```
gem "cocoapods-binary-cache", :git => "https://github.com/grab/cocoapods-binary-cache.git", :tag => "0.1.2"
```

And run:

```
bundle install
bundle exec pod binary prebuild
```
