### ISSUE TITLE
Error when execute `pod binary prebuild`

### ISSUE THREAD

**Issue by Leklef** [grab/cocoapods-binary-cache#36]
### Command

```
/Users/lenar/.rbenv/versions/2.7.2/bin/pod binary prebuild
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.18.0
Ruby lib dir : /Users/lenar/.rbenv/versions/2.7.2/lib
Repositories : bitbucket-interactiveplatform-ios.sdk.movika.com - git - https://bitbucket.org/interactiveplatform/ios.sdk.movika.com.git @ f6ab14c7d4582d433a35e31e326958d5f77dc0fa

               bitbucket-interactiveplatform-ios.sdk.player.interactive.film - git - https://bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git @ 8eddfd4cef3f35769395e7095c2323377b85bfe0

               master - git - https://github.com/CocoaPods/Specs.git @ 6b18aa56727760e998268032c3353ba9b7c5b6cf

               MovikaSDK_Dev - git - https://lenar-gilyazov@bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git @ a82f0ce82d4e46f10fe95aa7a507dc5208e5c94f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-binary       : 0.4.4
cocoapods-binary-cache : 0.1.9
cocoapods-deintegrate  : 1.0.4
cocoapods-plugins      : 1.0.0
cocoapods-rome         : 1.0.1
cocoapods-search       : 1.0.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'

plugin 'cocoapods-binary-cache'

config_cocoapods_binary_cache(
    cache_repo: {
      "default" => {
      "remote" => "https://lenar-gilyazov@bitbucket.org/lenar-gilyazov/binarypods.git",
      "local" => "~/.cocoapods-binary-cache/MKFoundation-libs"
    }
  },
  prebuild_config: "Release",
  dev_pods_enabled: true
)

target 'MKFoundation' do
  
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire', :binary => true
  pod 'R.swift'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'KeychainSwift'
  pod 'SwiftDate'
  pod 'MaterialShowcase'
  pod 'MovikaSDK_Dev', :git => 'https://bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git', :branch => 'dev', :binary => false

  target 'MKFoundationTests' do
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
```

### Error

```
ArgumentError - wrong number of arguments (given 1, expected 3..5)
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-rome-1.0.1/lib/cocoapods-rome/post_install.rb:33:in `xcodebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:64:in `build_for_sdk'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:21:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-binary/helper/build.rb:15:in `build'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:46:in `prebuild_frameworks!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:155:in `block in <class:PrebuildInstaller>'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:612:in `perform_post_install_actions'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:169:in `install!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/hooks/pre_install.rb:101:in `block in prebuild!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:118:in `title'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/hooks/pre_install.rb:99:in `prebuild!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/hooks/pre_install.rb:24:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/pod-binary/prebuild_hook.rb:5:in `block in <top (required)>'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `each'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:114:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:604:in `run_plugins_pre_install_hooks'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:224:in `block in prepare'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:220:in `prepare'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:159:in `install!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/command/executor/prebuilder.rb:31:in `block in prebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/command/executor/prebuilder.rb:29:in `prebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/command/executor/prebuilder.rb:18:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.9/lib/command/prebuild.rb:38:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/lenar/.rbenv/versions/2.7.2/bin/pod:23:in `load'
/Users/lenar/.rbenv/versions/2.7.2/bin/pod:23:in `<main>'
```

**Comment by trinhngocthuyen** [comment]
Hi. Thanks for reaching out!

From the stack trace, we can see that you're using `cocoapods-rome` in the project and there is a function collision of `xcodebuild` in the plugin and in `cocoapods-rome`. In this case, it uses the one in `cocoapods-rome` which leads to the issue.

Let me update the `xcodebuild` function to avoid function conflicts.

**Comment by trinhngocthuyen** [comment]
Hi @Leklef, The issue has been resolved and included in [0.1.10](https://github.com/grab/cocoapods-binary-cache/releases/tag/0.1.10). Kindly try it out.

Thanks for reporting the issue!

**Comment by Leklef** [comment]
Now I get this error
```
          $ xcodebuild -project /Users/lenar/Documents/02 Work/01
          iOSNative/DevPods/MKFoundation/_Prebuild/Pods.xcodeproj -target
          Alamofire -configuration Debug -sdk iphonesimulator -destination
          id=00CB3EDD-BA56-4FE0-810F-6D0EA6B31F2C ARCHS=x86_64
          ONLY_ACTIVE_ARCH=NO build 2>&1
```
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/lenar/.rbenv/versions/2.7.2/bin/pod binary prebuild
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.18.0
Ruby lib dir : /Users/lenar/.rbenv/versions/2.7.2/lib
Repositories : bitbucket-interactiveplatform-ios.sdk.movika.com - git - https://bitbucket.org/interactiveplatform/ios.sdk.movika.com.git @ f6ab14c7d4582d433a35e31e326958d5f77dc0fa

               bitbucket-interactiveplatform-ios.sdk.player.interactive.film - git - https://bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git @ 8eddfd4cef3f35769395e7095c2323377b85bfe0

               master - git - https://github.com/CocoaPods/Specs.git @ 6b18aa56727760e998268032c3353ba9b7c5b6cf

               MovikaSDK_Dev - git - https://lenar-gilyazov@bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git @ a82f0ce82d4e46f10fe95aa7a507dc5208e5c94f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-binary       : 0.4.4
cocoapods-binary-cache : 0.1.10
cocoapods-deintegrate  : 1.0.4
cocoapods-plugins      : 1.0.0
cocoapods-rome         : 1.0.1
cocoapods-search       : 1.0.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'

plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "remote" => "https://lenar-gilyazov@bitbucket.org/lenar-gilyazov/binarypods.git",
      "local" => "~/.cocoapods-binary-cache/MKFoundation-Pods"
    }
  },
  prebuild_config: "Debug",
  dev_pods_enabled: true
)

target 'MKFoundation' do
  
  use_frameworks!

  pod 'Alamofire', "5.3.0", :binary => true
  pod 'R.swift'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'KeychainSwift'
  pod 'SwiftDate'
  pod 'MaterialShowcase'
  pod 'MovikaSDK_Dev', :git => 'https://bitbucket.org/interactiveplatform/ios.sdk.player.interactive.film.git', :branch => 'dev'

  target 'MKFoundationTests' do
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
```

### Error

```
RuntimeError - Fail to build targets: ["Alamofire"]
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-rome/xcodebuild_raw.rb:44:in `xcodebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:65:in `build_for_sdk'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:22:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-binary/helper/build.rb:14:in `build'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:46:in `prebuild_frameworks!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:155:in `block in <class:PrebuildInstaller>'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:612:in `perform_post_install_actions'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:169:in `install!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/hooks/pre_install.rb:102:in `block in prebuild!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:118:in `title'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/hooks/pre_install.rb:100:in `prebuild!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/hooks/pre_install.rb:25:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/pod-binary/prebuild_hook.rb:5:in `block in <top (required)>'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `each'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:114:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:604:in `run_plugins_pre_install_hooks'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:224:in `block in prepare'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:220:in `prepare'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:159:in `install!'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/command/executor/prebuilder.rb:31:in `block in prebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/command/executor/prebuilder.rb:29:in `prebuild'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/command/executor/prebuilder.rb:18:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-binary-cache-0.1.10/lib/command/prebuild.rb:42:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/lenar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/lenar/.rbenv/versions/2.7.2/bin/pod:23:in `load'
/Users/lenar/.rbenv/versions/2.7.2/bin/pod:23:in `<main>'
```

**Comment by trinhngocthuyen** [comment]
```sh
         $ xcodebuild -project /Users/lenar/Documents/02 Work/01
          iOSNative/DevPods/MKFoundation/_Prebuild/Pods.xcodeproj -target
          Alamofire -configuration Debug -sdk iphonesimulator -destination
          id=00CB3EDD-BA56-4FE0-810F-6D0EA6B31F2C ARCHS=x86_64
          ONLY_ACTIVE_ARCH=NO build 2>&1
```
Hmm. Looks like the project path was not shell-escaped.

Could you please help try eliminating spacings in the project path `02 Work/01 iOSNative` -> `02_Work/01_iOSNative`?
We shall add shell-escape handling for this case in the meantime.

**Comment by Leklef** [comment]
Yes, it help. Thanks
