### ISSUE TITLE
Unable to push to remote repo

### ISSUE THREAD

**Issue by jianyaoang** [grab/cocoapods-binary-cache#37]
Thanks for creating and maintaining this plugin! Just discovered it and attempting to use it in my project.

Am facing an issue where I am unable to push to the remote repo. Followed the README steps to integrate this plugin, and was able to run and compile the app via `bundle exec pod install`. However, upon successful compilation, I tried to run `bundle exec pod binary push`, but met with an issue:

```
TypeError - no implicit conversion of nil into String
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a5325ada7980/lib/command/config.rb:10:in `expand_path'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a5325ada7980/lib/command/config.rb:10:in `initialize'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a5325ada7980/lib/command/binary.rb:14:in `new'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a5325ada7980/lib/command/binary.rb:14:in `prebuild_config'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a5325ada7980/lib/command/prebuild.rb:17:in `initialize'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/pod:23:in `load'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/pod:23:in `<main>'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/ruby_executable_hooks:24:in `eval'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/ruby_executable_hooks:24:in `<main>'
```

If it helps, here's my Podfile:

```
plugin "cocoapods-binary-cache"

source 'git@github.com:ProjectName/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'
inhibit_all_warnings!

workspace 'WorkspaceName'

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "remote" => "https://github.com/ProjectName/CocoapodsCache.git",
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug"
)

def cocoapods_cache
  pod 'YouTubePlayer', '0.7.0', :binary => true
end

target 'ProjectName' do
  project 'WorkspaceName.xcodeproj'
  cocoapods_cache
end
```

Additional details:

```
CocoaPods : 1.10.0
Ruby : ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin18]
RubyGems : 3.1.2
Xcode : 12.1
```

Appreciate any hint to move forward, thank you!!

**Comment by trinhngocthuyen** [comment]
Hi @jianyaoang, Thanks for reaching out for help!

I've just had a quick check for your case. The plugin version you're using is 0.1.2 (ref: `a5325ad`) which was outdated.
The issue should be fixed in recent releases. Kindly check out the latest one!

Thank you.

**Comment by jianyaoang** [comment]
@trinhngocthuyen Thanks for the quick reply! Updated to the latest 1.1.10, when i ran the `bundle exec pod binary push` command, I face this issue:

```
RuntimeError - Fail to run command 'git -C /Users/jianyaoang/.cocoapods-binary-cache/prebuilt-frameworks add .'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/command/executor/base.rb:21:in `git'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/command/executor/pusher.rb:15:in `block in run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/command/executor/pusher.rb:13:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bundler/gems/cocoapods-binary-cache-a380efa885f7/lib/command/push.rb:17:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/pod:23:in`oad'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/pod:23:in `<main>'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/ruby_executable_hooks:24:in `eval'
/Users/jianyaoang/.rvm/gems/ruby-2.5.6@project-ios/bin/ruby_executable_hooks:24:in `<main>’`
```

**Comment by trinhngocthuyen** [comment]
In this case, it fails to run `git add` command inside `~/.cocoapods-binary-cache/prebuilt-frameworks`. That implies the cache folder was not properly set up.

I assume you already ran a `fetch` command or a `prebuild` command beforehand. If not, please do so in order to have the cache-repo cloned to your local.

Also, you can cd to `~/.cocoapods-binary-cache/prebuilt-frameworks`, and try running `git add` to see what went wrong. That should give a clue of what was happening with the plugin as well.

**Comment by jianyaoang** [comment]
@trinhngocthuyen Sorry for the late reply, it's working now. Issue was because the push was towards the branch named `main` instead of `master`. Thank you!
