### ISSUE TITLE
RuntimeError - Fail to build targets: ["RealmSwift", "RxRealm"]

### ISSUE THREAD

**Issue by KPR7168** [grab/cocoapods-binary-cache#51]
I have a project that uses Objc & Swift. I'm trying to use this plugin to and it took me a while to realize that it only failed when I have `RealmSwift` & `RxRealm` in podfile.

### Report

* What did you do?

I ran `pod binary prebuild`

* What did you expect to happen?

To successfully prebuild all the pods and able to build my own project

* What happened instead?

It failed every time I have `RealmSwift` & `RxRealm` in my podfile.

### Command

```
/Users/username/.rvm/gems/ruby-2.6.3/bin/pod binary prebuild
```

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.2 (12B45b)
         Git : git version 2.29.1
Ruby lib dir : /Users/username/.rvm/rubies/ruby-2.6.3/lib
Repositories : privaterepo - git - git@github.com:PrivateRepo/Private-spec.git

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-binary       : 0.4.4
cocoapods-binary-cache : 0.1.11
cocoapods-deintegrate  : 1.0.4
cocoapods-playgrounds  : 1.2.2
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

### Podfile

```ruby
plugin "cocoapods-binary-cache"

source 'https://cdn.cocoapods.org/'

use_frameworks!
platform :ios, '11.0'

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "remote" => "git@github.com:PrivateRepo/Private-spec.git",
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug"
)

def binary_pod(name, *args)
  pod name, args, :binary => true
end

def share_pods
  binary_pod 'AFNetworking', '~> 3.0'
  binary_pod 'SVProgressHUD','~>1.1.3'
  binary_pod 'RealmSwift'
  binary_pod 'BlocksKit'
  binary_pod 'SDWebImage', '~>3.7'
  binary_pod 'MTAnimation'
  binary_pod 'Charts'
  binary_pod 'pop'
  binary_pod 'UIView+Helpers'
  binary_pod 'OCMock'
  binary_pod 'Appirater'
  binary_pod 'Reachability'
  binary_pod 'MJRefresh'
  binary_pod 'SnowplowTracker'
  binary_pod 'Adjust'
  binary_pod 'FXBlurView'
  binary_pod 'FBSDKCoreKit'
  binary_pod 'FBSDKLoginKit'
  binary_pod 'Fabric'
  binary_pod 'GoogleSignIn'
  binary_pod 'Cosmos', '~> 20.0'
  binary_pod 'Hero'
  binary_pod 'YYText'
  binary_pod 'Firebase/Crashlytics'
  binary_pod 'Firebase/Analytics'
  binary_pod 'Firebase/Performance'
  binary_pod 'RMStore', '~> 0.7'
  binary_pod 'FittedSheets'
  binary_pod 'INSPhotoGallery'
  binary_pod 'OFToastieBoy', '~>1.0.6' 
  binary_pod 'SkeletonView'
  binary_pod 'TwilioVoice', '~> 6.0.0'
  binary_pod 'lottie-ios'
  binary_pod 'RxSwift', '~> 5'
  binary_pod 'RxCocoa', '~> 5'
  binary_pod 'RxOptional'
  binary_pod 'MessageKit'
  binary_pod 'RxRealm'
  binary_pod 'JTAppleCalendar'
  binary_pod 'Apollo'
  binary_pod 'SnapKit'
  binary_pod 'OFColorful'
  binary_pod 'OFDatePicker'
  binary_pod 'UXCam'
end

target 'MainTarget' do
  inhibit_all_warnings!
  share_pods
end

target 'TestTarget' do
  binary_pod 'Realm/Headers'
end

target 'UITestTarget' do
  inhibit_all_warnings!
  share_pods
  binary_pod 'RxBlocking', '~> 5'
  binary_pod 'RxTest', '~> 5'
  binary_pod 'Hippolyte'
end

post_install do |installer_representation|
  libs = ['INSPhotoGallery', 'INSNibLoading']
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['EXCLUDED_ARCHS[sdk=watchsimulator*]'] = 'arm64'
      config.build_settings['EXCLUDED_ARCHS[sdk=appletvsimulator*]'] = 'arm64'
      if libs.include? target.name
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
```

### Error

```
RuntimeError - Fail to build targets: ["RealmSwift", "RxRealm"]
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-rome/xcodebuild_raw.rb:44:in `xcodebuild'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:66:in `build_for_sdk'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-rome/xcodebuild_command.rb:22:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-binary/helper/build.rb:14:in `build'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:46:in `prebuild_frameworks!'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-binary/prebuild.rb:155:in `block in <class:PrebuildInstaller>'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:612:in `perform_post_install_actions'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:169:in `install!'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/hooks/pre_install.rb:102:in `block in prebuild!'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:118:in `title'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/hooks/pre_install.rb:100:in `prebuild!'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/hooks/pre_install.rb:25:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/pod-binary/prebuild_hook.rb:5:in `block in <top (required)>'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `each'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/hooks_manager.rb:114:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:604:in `run_plugins_pre_install_hooks'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:224:in `block in prepare'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:220:in `prepare'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:159:in `install!'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/command/executor/prebuilder.rb:31:in `block in prebuild'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/command/executor/prebuilder.rb:29:in `prebuild'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/command/executor/prebuilder.rb:18:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-binary-cache-0.1.11/lib/command/prebuild.rb:42:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/username/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/username/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
/Users/username/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'

**Comment by KPR7168** [comment]
I updated my Realm version, then it seems to fix it.
