### ISSUE TITLE
Error with static framework using *.xib resources

### ISSUE THREAD

**Issue by trinhngocthuyen** [grab/cocoapods-binary-cache#7]
When running with **static frameworks** that have **resources** declared by `spec.resources = [...]`, it throws an error saying that **the `*.xib` file does not exist**.

This happens to me when using [`GTMOAuth2`](https://github.com/google/gtm-oauth2/blob/v1.1.6/GTMOAuth2.podspec) as a static framework.
```
s.ios.resources = 'Source/Touch/*.xib'
```

The issue occurred in the integration step when we generate the project file.

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/chris.thuyen/dev/pod-cache-demo/Pods/_Prebuild/GeneratedFrameworks/GTMOAuth2/GTMOAuth2.framework/GTMOAuth2ViewTouch.xib // <------------ HERE
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `reference_for_path'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:266:in `add_file_reference'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:220:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `each'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `block in add_file_accessors_paths_to_pods_group'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `each'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `add_file_accessors_paths_to_pods_group'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:126:in `block in add_resources'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:125:in `add_resources'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:49:in `install!'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator.rb:101:in `block in install_file_references'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator.rb:99:in `install_file_references'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:295:in `block in create_and_save_projects'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/bin/pod:23:in `load'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/bin/pod:23:in `<main>'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users/chris.thuyen/bundle_dir/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

After a quick investigation, I figured out that after compiling the framework, the `*.xib` resource files were **copied to the framework as `*.nib` files**.

**Comment by trinhngocthuyen** [comment]
Should be resolved in https://github.com/grab/cocoapods-binary-cache/commit/1ac05cd4f0528e86d0d6fa7f080882d16363dfb4
