### ISSUE TITLE
Pod Binary Push Fails 

### ISSUE THREAD

**Issue by sashi01** [grab/cocoapods-binary-cache#93]
### Checklist
- [x] Updated the plugin to the latest version
- [x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

#### Command executed
bundle exec pod binary push

#### What went wrong?
Push failed 

#### Stack trace
Error

```
RuntimeError - Fail to run command 'git -C /Users/sashi/Documents/mono-ios/ios-mobile/_LocalBinaryPods add .'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/command/executor/base.rb:30:in `git'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/command/executor/pusher.rb:30:in `commit_and_push_cache'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/command/executor/pusher.rb:17:in `block in run'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/ui.rb:5:in `block in step'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/cocoapods-binary-cache/ui.rb:5:in `step'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/command/executor/pusher.rb:13:in `run'
/Users/sashi/.bundle/ruby/2.6.0/cocoapods-binary-cache-f73781c33d07/lib/command/push.rb:17:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

#### Plugin version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
cocoapods 1.10.1

#### Installed CocoaPods plugins
Installed CocoaPods Plugins:
    - cocoapods-binary-cache : 0.1.14 (pre_install and post_install hooks)
    - cocoapods-deintegrate  : 1.0.4
    - cocoapods-plugins      : 1.0.0
    - cocoapods-search       : 1.0.0
    - cocoapods-trunk        : 1.5.0
    - cocoapods-try          : 1.2.0

**Comment by sashi01** [comment]
Is it because following are included in `.gitignore` , but i do not want to track them

`**/Pods/
**/_Prebuild
**/_Prebuild_delta
**/_LocalBinaryPods`

**Comment by trinhngocthuyen** [comment]
This is duplicated with https://github.com/grab/cocoapods-binary-cache/issues/94

It's correct to ignore `Pods`, `_Prebuild` and `_Prebuild_delta`. For `_LocalBinaryPods`, that might be the case.
May I suggest changing the cache dir to somewhere outside the project (ex. `~/LocalBinaryPods`) and try again?

**Comment by sashi01** [comment]
Caused due to different configuration cache images been pushed to repo. Clearing the repo solves it. Thx !
